import { expect,test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { readFile } from 'node:fs/promises';

test('public library, note reader, cases, and responsive layout work',async({page})=>{await page.goto('/notes');await expect(page.getByRole('heading',{name:'Your course notes, thoughtfully organized.'})).toBeVisible();await expect(page.locator('.course-card')).toHaveCount(12);const first=page.locator('.course-card').first();await expect(first).toBeVisible();await first.click();await expect(page.getByRole('heading',{name:'Course syllabus'})).toBeVisible();await page.locator('.module-row').first().click();await expect(page.locator('#note-content')).toBeVisible();await page.goto('/case-studies');await expect(page.getByRole('heading',{name:'Original case studies.'})).toBeVisible();await expect(page.locator('.case-card').first()).toBeVisible();const width=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));expect(width.scroll).toBeLessThanOrEqual(width.client+1);const violations=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa']).analyze();expect(violations.violations).toEqual([])});

test('semester podcasts and interactive sessions use published course content',async({page})=>{await page.goto('/podcasts');await expect(page.getByRole('heading',{name:'Course conversations.'})).toBeVisible();await expect(page.getByText('A conversation between Mira and Arun')).toBeVisible();await expect(page.locator('.dialogue-transcript button')).toHaveCount(12);await page.getByRole('tab',{name:'Term 2'}).click();await expect(page.locator('.episode-list button')).toHaveCount(4);await page.goto('/interactive');await expect(page.getByRole('heading',{name:'Interactive study lab.'})).toBeVisible();await expect(page.getByText(/Step 1 of/)).toBeVisible();await page.getByRole('button',{name:/Next/}).click();await expect(page.getByText(/Step 2 of/)).toBeVisible();await page.getByRole('button',{name:'Learn more'}).click();await expect(page.getByText('Learn more',{exact:true})).toBeVisible();const width=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));expect(width.scroll).toBeLessThanOrEqual(width.client+1)});

test('administrator can sign in and open the syllabus editor',async({browser})=>{test.skip(test.info().project.name==='mobile','Admin workflow is covered at desktop width.');const access=await readFile('.local/admin-access.txt','utf8');const email=/Email:\s*(.+)/.exec(access)?.[1]?.trim();const password=/Password:\s*(.+)/.exec(access)?.[1]?.trim();expect(email).toBeTruthy();expect(password).toBeTruthy();const context=await browser.newContext({baseURL:'http://localhost:3001'});const page=await context.newPage();await page.goto('/login');await page.getByLabel('Email').fill(email!);await page.getByLabel('Password').fill(password!);await page.getByRole('button',{name:'Sign in to administration'}).click();await expect(page.getByRole('heading',{name:'Good material. Clearer understanding.'})).toBeVisible();await page.getByRole('link',{name:'Syllabus & notes'}).click();await expect(page.getByRole('heading',{name:'Syllabus & study notes'})).toBeVisible();await expect(page.locator('table tbody tr').first()).toBeVisible();await context.close()});
