'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, Cable, CheckCircle2, ChevronLeft, ChevronRight, CircleAlert, Layers, Network, Pause, Play, Radio, RotateCcw, Server, ShieldCheck, Sliders, Tv, Wifi } from 'lucide-react';

const hops = [
  ['Hostel laptop', 'The click: generating a request', 'Application data becomes a request for the first video segment.', 'The browser creates a manifest request. It knows the service endpoint, not the route or cable.'],
  ['Transport stack', 'Stream segmentation and ports', 'The operating system gives the message a process endpoint and delivery rules.', 'TCP or QUIC adds sequencing, congestion behaviour, and the destination service port.'],
  ['IP routing logic', 'Global addressing and the subnet decision', 'The network layer chooses whether the destination is local or remote.', 'The host compares the destination address with its subnet and sends remote traffic to the default gateway.'],
  ['Wi-Fi airwave', 'Wireless framing and modulation', 'The local access point turns frames into radio symbols.', 'The link adds MAC addresses and error detection, then transmits the signal over a shared channel.'],
  ['Switch and gateway', 'Local switching to a border router', 'Frames cross the local network before the router chooses the next IP hop.', 'A switch forwards within the LAN. The gateway removes the local frame and routes the packet onward.'],
  ['Provider core', 'High-capacity transit through the network', 'Routers and optical links carry the packet between networks.', 'Each router selects another hop. The local frame changes at every link while the routed destination remains meaningful.'],
  ['Edge server', 'Content delivery close to the learner', 'The response begins its return journey from an available service edge.', 'The server reverses the stack and sends the video segment back through the same layered responsibilities.'],
] as const;

const faults = {
  physical: ['iwconfig wlan0', 'Signal level=-89 dBm  Noise level=-90 dBm', 'Link Quality=8/70  SNR=1 dB', 'ping 192.168.1.1 → 100% packet loss'],
  link: ['ethtool -S eth0 | grep crc', 'rx_crc_errors: 41820', 'rx_frame_errors: 18402', 'Frames are discarded before IP sees them'],
  network: ['ping 1.1.1.1 → 14.2 ms', 'nslookup portal.example', 'DNS server refused the request', 'Routing works; name resolution does not'],
  transport: ['ping portal.example → reachable', 'nc -zv portal.example 443', 'TCP connection timed out', 'A firewall or listener blocks the service port'],
  application: ['curl -I https://portal.example', 'HTTP/2 403 Forbidden', 'TLS completed successfully', 'The remaining failure belongs to the application'],
} as const;

export function ComputerNetworksModule() {
  const [section, setSection] = useState('transit');
  const [hop, setHop] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [bits, setBits] = useState('10110010');
  const [topology, setTopology] = useState('star');
  const [layer, setLayer] = useState(5);
  const [fault, setFault] = useState<keyof typeof faults>('physical');
  const parsedBits = useMemo(() => bits.replace(/[^01]/g, '').slice(0, 16).split(''), [bits]);

  useEffect(() => {
    if (!playing) return;
    const timer = window.setInterval(() => setHop(current => current >= hops.length - 1 ? (setPlaying(false), current) : current + 1), 2600);
    return () => window.clearInterval(timer);
  }, [playing]);

  const nav = [
    ['transit', 'End-to-end transit'], ['signals', 'Signal encoding'], ['layers', 'Layering & OSI'], ['diagnostic', 'Diagnostic lab'],
  ];
  return <div className="cn-module min-h-screen bg-slate-50 text-slate-900 -mx-4 sm:-mx-8 -mt-8">
    <header className="sticky top-0 z-20 border-b border-slate-200/80 bg-white/95 backdrop-blur-md">
      <div className="mx-auto flex h-16 max-w-6xl items-center justify-between gap-4 px-4 sm:px-6">
        <div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-900 text-sm font-bold text-white"><span className="text-rose-500">N</span>1</div><div className="hidden sm:block text-sm font-bold tracking-tight">Computer Networks <span className="mx-2 text-slate-300">/</span><span className="font-semibold text-slate-600">Unit 1 Case Study</span></div></div>
        <nav className="hidden gap-5 text-xs font-semibold text-slate-600 md:flex">{nav.map(([id, label]) => <button key={id} onClick={() => setSection(id)} className={section === id ? 'font-bold text-rose-600' : 'hover:text-slate-900'}>{label}</button>)}</nav>
        <div className="flex items-center gap-2 text-xs"><span className="hidden text-slate-500 sm:inline">CN101 · Module 1</span><button onClick={() => { setSection('transit'); document.getElementById('cn-transit')?.scrollIntoView({ behavior: 'smooth' }); }} className="rounded-lg bg-slate-900 px-3.5 py-1.5 font-semibold text-white shadow-sm hover:bg-slate-800">Transit simulator</button></div>
      </div>
      <div className="flex gap-4 overflow-x-auto border-t border-slate-200/60 bg-white px-4 py-2 text-xs font-semibold text-slate-600 md:hidden">{nav.map(([id, label]) => <button key={id} onClick={() => setSection(id)} className={`whitespace-nowrap ${section === id ? 'font-bold text-rose-600' : ''}`}>{label}</button>)}</div>
    </header>

    <section className="border-b border-slate-200/80 bg-white py-12 sm:py-16"><div className="mx-auto max-w-4xl px-4 sm:px-6"><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-rose-600"><span>Case study</span><span className="text-slate-300">·</span><span>Computer Networks Unit 1</span></div><h1 className="text-3xl font-extrabold tracking-tight text-slate-900 sm:text-5xl">What actually happens when you open a video?</h1><div className="mt-4 flex flex-wrap gap-3 text-xs text-slate-500"><span>Campus laptop to edge server</span><span>·</span><span>7 hops</span><span>·</span><span>OSI and Internet architecture</span></div><p className="mt-6 text-base leading-relaxed text-slate-700 sm:text-lg">A single click crosses application software, transport rules, IP networks, local links, and physical media. This unit lets you move through that journey, inspect the signals, compare layers, and diagnose a failure with evidence.</p></div></section>

    <main className="mx-auto flex max-w-5xl flex-col gap-16 px-4 py-10 sm:px-6">
      <section id="cn-transit" className="scroll-mt-24"><div className="mb-6"><span className="text-xs font-bold uppercase tracking-wider text-slate-500">Interactive simulation</span><h2 className="text-2xl font-bold tracking-tight">The end-to-end transit path</h2><p className="text-sm text-slate-600">Follow one request from the learner’s laptop to a nearby content edge.</p></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3 text-xs"><span className="font-bold uppercase tracking-wide">Hop {hop + 1} of {hops.length}</span><span className="text-slate-500">{hops[hop][0]}</span></div><div className="grid gap-6 p-5 md:grid-cols-[220px_1fr]"><div className="grid gap-2">{hops.map((item, index) => <button key={item[0]} onClick={() => { setHop(index); setPlaying(false); }} className={`rounded-xl border p-3 text-left transition ${index === hop ? 'border-rose-300 bg-rose-50 ring-2 ring-rose-100' : 'border-slate-200 hover:border-slate-300'}`}><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500">0{index + 1}</span><strong className="mt-1 block text-sm">{item[0]}</strong></button>)}</div><div className="rounded-2xl bg-slate-950 p-6 text-white"><div className="mb-4 flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-wider text-rose-300">{hops[hop][1]}</span><Network size={20} className="text-rose-300" /></div><p className="text-lg leading-relaxed text-slate-100">{hops[hop][2]}</p><div className="mt-6 rounded-xl border border-slate-700 bg-slate-900 p-4 text-sm leading-relaxed text-slate-300">{hops[hop][3]}</div><div className="mt-6 flex gap-2"><button className="rounded-lg bg-rose-500 px-4 py-2 text-xs font-bold text-white" onClick={() => setPlaying(!playing)}>{playing ? <><Pause size={14} className="mr-2 inline" />Pause path</> : <><Play size={14} className="mr-2 inline" />Play path</>}</button><button className="rounded-lg border border-slate-600 px-4 py-2 text-xs font-bold" onClick={() => { setHop(0); setPlaying(false); }}><RotateCcw size={14} className="mr-2 inline" />Restart</button></div></div></div></div></section>

      <section id="cn-signals" className="scroll-mt-24"><div className="mb-6"><span className="text-xs font-bold uppercase tracking-wider text-slate-500">Physical layer workbench</span><h2 className="text-2xl font-bold tracking-tight">Signal encoding and media</h2><p className="text-sm text-slate-600">Change the bits and see why timing and transitions matter to a receiver.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label className="block text-xs font-bold uppercase tracking-wide text-slate-600">Bit pattern<input value={bits} onChange={event => setBits(event.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2 font-mono text-lg tracking-[.35em]" inputMode="numeric" maxLength={16} /></label><div className="mt-6 grid gap-4 md:grid-cols-2">{[['NRZ-L', 'A steady level represents each bit.', '#2563eb'], ['Manchester', 'A mid-bit transition supplies timing.', '#e11d48'], ['Bipolar AMI', 'Ones alternate polarity while zero rests.', '#4f46e5'], ['Optical or radio', 'The signal travels through a chosen medium.', '#0d9488']].map(([name, copy, color]) => <div key={name} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><strong>{name}</strong><span className="text-xs text-slate-500">{copy}</span></div><div className="mt-4 flex h-16 items-center gap-1 rounded-lg bg-slate-50 px-3">{parsedBits.map((bit, index) => <div key={`${bit}-${index}`} className="relative h-10 flex-1 border-r border-dashed border-slate-200"><div className="absolute left-1 right-1 rounded" style={{ height: name === 'Manchester' ? 3 : 6, top: name === 'Manchester' ? (bit === '1' ? 10 : 28) : (bit === '1' ? 8 : 34), background: color }} /></div>)}</div></div>)}</div></div></section>

      <section id="cn-layers" className="scroll-mt-24"><div className="mb-6"><span className="text-xs font-bold uppercase tracking-wider text-slate-500">Layering and protocol suites</span><h2 className="text-2xl font-bold tracking-tight">Five-layer Internet view</h2><p className="text-sm text-slate-600">Select a layer to inspect what it adds and which unit it carries.</p></div><div className="grid gap-3 md:grid-cols-2">{[[5, 'Application', 'Data / message', 'HTTP, DNS, TLS, video delivery'], [4, 'Transport', 'Segment / datagram', 'TCP, UDP, QUIC, ports'], [3, 'Network', 'IP packet', 'IPv4, IPv6, ICMP, routing'], [2, 'Data link', 'Frame', 'Ethernet, Wi-Fi, MAC, CRC'], [1, 'Physical', 'Bits', 'Copper, fibre, radio, encoding']].map(([number, name, pdu, protocols]) => <button key={number} onClick={() => setLayer(Number(number))} className={`rounded-xl border p-4 text-left transition ${layer === number ? 'border-slate-900 bg-slate-50 ring-2 ring-slate-900/10' : 'border-slate-200 bg-white hover:border-slate-300'}`}><div className="flex items-center justify-between"><strong>{name} layer</strong><span className="font-mono text-[10px] text-slate-500">{pdu}</span></div><div className="mt-2 font-mono text-xs text-rose-600">{protocols}</div><p className="mt-2 text-xs leading-relaxed text-slate-600">{layer === number ? 'This layer is selected. Follow its boundary when deciding what evidence to collect next.' : 'Select to inspect this layer in the encapsulation chain.'}</p></button>)}</div></section>

      <section id="cn-diagnostic" className="scroll-mt-24"><div className="mb-6"><span className="text-xs font-bold uppercase tracking-wider text-slate-500">Practical network diagnosis</span><h2 className="text-2xl font-bold tracking-tight">Wi-Fi connected, but the portal will not load</h2><p className="text-sm text-slate-600">Test from the bottom of the stack upward and stop at the first failing boundary.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex flex-wrap gap-2">{Object.keys(faults).map(key => <button key={key} onClick={() => setFault(key as keyof typeof faults)} className={`rounded-lg px-3 py-2 text-xs font-semibold capitalize ${fault === key ? 'bg-slate-900 text-white' : 'border border-slate-200 bg-slate-50 text-slate-700'}`}>{key}</button>)}</div><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><pre className="rounded-xl bg-slate-950 p-5 text-xs leading-7 text-slate-200">{faults[fault].join('\n')}</pre><div className="rounded-xl border border-rose-200 bg-rose-50 p-5"><strong className="text-xs uppercase tracking-wide text-rose-900">Engineering deduction</strong><p className="mt-3 text-sm leading-relaxed text-rose-900">{fault === 'physical' ? 'The signal-to-noise ratio is too low. Improve placement, channel selection, or the physical link before changing application settings.' : fault === 'link' ? 'Frames arrive corrupted and are discarded at the link boundary. Check the medium, interface, and local error counters.' : fault === 'network' ? 'The route works but the name service does not. Test DNS separately from raw IP reachability.' : fault === 'transport' ? 'Lower layers work, but the service port cannot complete a connection. Check the listener and firewall policy.' : 'The network path is healthy enough to return an application response. Investigate the service, identity, or content policy.'}</p><div className="mt-5 flex items-center gap-2 text-xs font-semibold text-rose-800"><CheckCircle2 size={15} />One hypothesis, one test, one recorded result.</div></div></div></div></section>
    </main>
    <footer className="border-t border-slate-200 bg-white py-8 text-xs text-slate-500"><div className="mx-auto flex max-w-5xl flex-col justify-between gap-3 px-4 sm:flex-row sm:px-6"><strong className="text-slate-800">Unit 1 Computer Networks</strong><span>Independent interactive study module</span></div></footer>
  </div>;
}
