'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, CheckCircle2, Network, RotateCcw, ShieldCheck } from 'lucide-react';

const units = [
  ['transit', 'Network journey'], ['subnetting', 'Subnet planner'], ['vlans', 'VLAN lab'],
  ['nat', 'NAT/PAT lab'], ['routing', 'Routing lab'], ['forwarding', 'Forwarding'],
  ['diagnosis', 'Fault diagnosis'], ['recall', 'Knowledge check'],
] as const;
type Section = typeof units[number][0];

const toNumber = (ip: string) => ip.split('.').reduce((value, octet) => (value * 256n) + BigInt(Number(octet)), 0n);
const toIp = (value: bigint) => [24n, 16n, 8n, 0n].map(shift => Number((value >> shift) & 255n)).join('.');
const maskFor = (prefix: number) => ((0xffffffffn << BigInt(32 - prefix)) & 0xffffffffn);
const networkInfo = (ip: string, prefix: number) => {
  const address = toNumber(ip);
  const mask = maskFor(prefix);
  const network = address & mask;
  const broadcast = network | (0xffffffffn ^ mask);
  const total = 2 ** (32 - prefix);
  return { network: toIp(network), broadcast: toIp(broadcast), first: prefix <= 30 ? toIp(network + 1n) : 'Point-to-point', last: prefix <= 30 ? toIp(broadcast - 1n) : 'Point-to-point', total, usable: prefix <= 30 ? total - 2 : total };
};

const stages = [
  ['Device and access VLAN', 'A handheld scanner joins the operations Wi-Fi. Its access network places the device in the scanner VLAN.'],
  ['Trunk and gateway', 'An 802.1Q trunk carries selected VLANs to a Layer 3 gateway, which routes only traffic permitted by policy.'],
  ['Address translation', 'At the edge, a stateful NAT/PAT mapping may translate the private source tuple for an outbound IPv4 flow.'],
  ['Upstream routing', 'The provider and the cooperative exchange reachability according to their routing policies.'],
  ['Service network', 'Internal routers forward toward a fictional dispatch service; link-state routing may be used inside its routing domain.'],
  ['Application and response', 'The service processes the request and returns a response over a path that may differ from the forward path.'],
  ['Physical dispatch', 'A separate operations system uses the service result to prepare a parcel. This physical action is outside packet forwarding.'],
] as const;

const questions = [
  { q: 'A /26 IPv4 subnet has how many conventional usable host addresses?', options: ['62', '64', '126'], answer: 0, why: 'A /26 leaves 6 host bits: 64 total addresses, with network and directed-broadcast addresses reserved in conventional subnets.' },
  { q: 'What does an 802.1Q tag communicate across a VLAN trunk?', options: ['The VLAN identity for the tagged frame', 'The global internet route to the destination', 'The translated TCP source port'], answer: 0, why: 'The VLAN tag lets the receiving network device associate the frame with the correct Layer 2 broadcast domain.' },
  { q: 'Which description best separates OSPF and BGP?', options: ['OSPF is link-state routing within a routing domain; BGP exchanges reachability between autonomous systems under policy.', 'OSPF translates private ports; BGP assigns access VLANs.', 'They are two names for the same shortest-path algorithm.'], answer: 0, why: 'OSPF is an interior link-state protocol, while BGP is used for inter-domain reachability and policy.' },
];

function SectionNav({ active, onSelect }: { active: Section; onSelect: (id: Section) => void }) {
  return <nav aria-label="Unit 2 lab sections" className="flex gap-2 overflow-x-auto border-y border-slate-200 bg-white px-4 py-3 sm:px-6">{units.map(([id, label]) => <button key={id} onClick={() => onSelect(id)} className={`whitespace-nowrap rounded-full px-3 py-2 text-xs font-semibold ${active === id ? 'bg-slate-900 text-white' : 'border border-slate-200 text-slate-600 hover:bg-slate-50'}`}>{label}</button>)}</nav>;
}

export function ComputerNetworksUnitTwoModule() {
  const [active, setActive] = useState<Section>('transit');
  const [stage, setStage] = useState(0);
  const [host, setHost] = useState('192.168.10.75');
  const [prefix, setPrefix] = useState(26);
  const [vlanMode, setVlanMode] = useState<'access' | 'trunk'>('trunk');
  const [nativeA, setNativeA] = useState('99');
  const [nativeB, setNativeB] = useState('99');
  const [nextPort, setNextPort] = useState(40001);
  const [natRows, setNatRows] = useState<string[]>([]);
  const [primaryUp, setPrimaryUp] = useState(true);
  const [backupUp, setBackupUp] = useState(true);
  const [question, setQuestion] = useState(0);
  const [answer, setAnswer] = useState<number | null>(null);
  const subnet = useMemo(() => {
    const octets = host.split('.');
    const valid = octets.length === 4 && octets.every(part => /^\d{1,3}$/.test(part) && Number(part) <= 255);
    return valid ? networkInfo(host, prefix) : null;
  }, [host, prefix]);
  const vlanMismatch = nativeA.trim() !== nativeB.trim();
  const transit = stages[stage] ?? stages[0];
  const quiz = questions[question];
  const changeSection = (id: Section) => { setActive(id); document.getElementById(`cn2-${id}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); };

  return <div className="cn-module -mx-4 -mt-8 min-h-screen bg-slate-50 text-slate-900 sm:-mx-8">
    <header className="sticky top-0 z-20 border-b border-slate-200 bg-white/95 backdrop-blur-md"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between gap-4 px-4 sm:px-6"><div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center rounded-lg bg-slate-900 text-sm font-bold text-white"><span className="text-rose-400">N</span>2</div><strong className="hidden text-sm sm:block">Computer Networks <span className="mx-2 text-slate-300">/</span><span className="text-slate-600">Unit 2 Network Design Lab</span></strong></div><div className="flex items-center gap-3 text-xs"><span className="hidden text-slate-500 sm:inline">CN101 · Module 2</span><Link href="/interactive?course=computer-networks&module=computer-networks-unit-2" className="rounded-lg bg-slate-900 px-3.5 py-2 font-semibold text-white">Open full study lab</Link></div></div><SectionNav active={active} onSelect={changeSection} /></header>
    <main className="mx-auto grid w-full max-w-5xl grid-cols-[minmax(0,1fr)] gap-10 px-4 py-10 sm:px-6">
      <section className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-10"><p className="text-xs font-bold uppercase tracking-widest text-rose-600">Independent study companion · Unit 2</p><h1 className="mt-3 max-w-3xl text-3xl font-extrabold tracking-tight sm:text-5xl">Design a network that can explain itself.</h1><p className="mt-4 max-w-3xl leading-7 text-slate-600">Plan addresses, separate traffic, follow a translated flow, and test what changes when a route fails. Work through one fictional delivery cooperative from its access network to its dispatch service.</p><p className="mt-4 text-xs text-slate-500">All organization names, addresses, logs, and examples here are fictional. This material is not an official institutional platform or a description of any provider’s private network.</p></section>
      <section id="cn2-transit" className="scroll-mt-32"><SectionTitle eyebrow="End-to-end case study" title="Follow a dispatch request" text="Move through the network boundary by boundary. The final parcel handoff is an application outcome, not a network-layer operation."/><div className="grid gap-5 rounded-2xl border border-slate-200 bg-white p-5 md:grid-cols-[220px_1fr]"><div className="grid gap-2">{stages.map(([name], index) => <button key={name} onClick={() => setStage(index)} className={`rounded-xl border p-3 text-left text-sm ${stage === index ? 'border-rose-300 bg-rose-50' : 'border-slate-200'}`}><span className="mr-2 font-mono text-xs text-slate-400">0{index + 1}</span>{name}</button>)}</div><div className="rounded-2xl bg-slate-950 p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest text-rose-300">Checkpoint {stage + 1} / {stages.length}</p><h3 className="mt-3 text-2xl font-bold">{transit[0]}</h3><p className="mt-3 leading-7 text-slate-300">{transit[1]}</p><div className="mt-6 flex gap-2"><button disabled={stage === 0} onClick={() => setStage(stage - 1)} className="rounded-lg border border-slate-600 px-4 py-2 text-sm disabled:opacity-40">Previous</button><button onClick={() => setStage((stage + 1) % stages.length)} className="rounded-lg bg-rose-500 px-4 py-2 text-sm font-bold">Next checkpoint</button></div></div></div></section>
      <section id="cn2-subnetting" className="scroll-mt-32"><SectionTitle eyebrow="Hands-on lab 1" title="Subnet and prefix calculator" text="Change the address and prefix; the network, broadcast, and conventional host range update together."/><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">IPv4 address<input aria-label="IPv4 address" value={host} onChange={event => setHost(event.target.value)} className="rounded-lg border border-slate-300 px-3 py-2 font-mono font-normal" inputMode="decimal" /></label><label className="grid gap-2 text-sm font-semibold">Prefix length · /{prefix}<input aria-label="Prefix length" type="range" min="8" max="30" value={prefix} onChange={event => setPrefix(Number(event.target.value))} /></label></div>{subnet ? <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[['Subnet mask', toIp(maskFor(prefix))], ['Network address', `${subnet.network}/${prefix}`], ['Broadcast address', subnet.broadcast], ['First conventional host', subnet.first], ['Last conventional host', subnet.last], ['Usable host addresses', String(subnet.usable)]].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-4"><span className="block text-xs text-slate-500">{label}</span><strong className="mt-1 block font-mono text-sm">{value}</strong></div>)}</div> : <p role="alert" className="mt-4 text-sm font-semibold text-rose-700">Enter four IPv4 octets between 0 and 255.</p>}<p className="mt-4 text-xs leading-5 text-slate-500">For prefixes /8–/30 this uses the conventional network and directed-broadcast reservation. /31 point-to-point links have a special host-count rule.</p></div><VlsmPlanner /></section>
      <section id="cn2-vlans" className="scroll-mt-32"><SectionTitle eyebrow="Hands-on lab 2" title="Access ports, trunks, and VLAN boundaries" text="Choose the port role and compare trunk settings. A VLAN tag identifies a Layer 2 domain; routing between VLANs still needs a Layer 3 gateway and an allowing policy."/><div className="grid gap-5 rounded-2xl border border-slate-200 bg-white p-5 lg:grid-cols-2"><div><div className="flex gap-2"><button onClick={() => setVlanMode('access')} className={`rounded-lg px-4 py-2 text-sm font-semibold ${vlanMode === 'access' ? 'bg-slate-900 text-white' : 'border border-slate-200'}`}>Access port</button><button onClick={() => setVlanMode('trunk')} className={`rounded-lg px-4 py-2 text-sm font-semibold ${vlanMode === 'trunk' ? 'bg-slate-900 text-white' : 'border border-slate-200'}`}>802.1Q trunk</button></div><div className="mt-4 rounded-xl bg-slate-950 p-5 font-mono text-sm text-slate-200">{vlanMode === 'access' ? 'END DEVICE → ACCESS PORT → VLAN 20\nFrame assigned to configured VLAN at the port' : 'SWITCH A → 802.1Q TRUNK → SWITCH B\n[Ethernet header] [VLAN ID 20] [payload]'}</div><label className="mt-4 block text-sm">Allowed VLANs on trunk<input className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2 font-mono text-sm" defaultValue="10,20,30" aria-label="Allowed VLANs on trunk" /></label></div><div className="rounded-xl border border-slate-200 p-4"><h3 className="font-bold">Compare native VLAN settings</h3><p className="mt-1 text-xs leading-5 text-slate-500">Untagged traffic on a trunk is associated with the configured native VLAN. Mismatches need investigation; exact symptoms vary by design and equipment.</p><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-xs">Switch A native VLAN<input aria-label="Switch A native VLAN" value={nativeA} onChange={event => setNativeA(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" /></label><label className="text-xs">Switch B native VLAN<input aria-label="Switch B native VLAN" value={nativeB} onChange={event => setNativeB(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" /></label></div><p role="status" className={`mt-4 rounded-lg p-3 text-sm ${vlanMismatch ? 'bg-amber-50 text-amber-900' : 'bg-emerald-50 text-emerald-900'}`}>{vlanMismatch ? 'Settings differ. Check both trunk ends and the VLAN policy before sending traffic.' : `Both ends agree on VLAN ${nativeA || '—'}. Confirm the VLAN exists and is allowed on the trunk.`}</p></div></div></section>
      <section id="cn2-nat" className="scroll-mt-32"><SectionTitle eyebrow="Hands-on lab 3" title="Create a stateful PAT mapping" text="Add a fictional outbound flow and inspect the address-and-port mapping used to associate its reply."/><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-600">Inside endpoint: <code className="font-mono">10.24.0.25:51514</code> · Service: <code className="font-mono">203.0.113.80:443</code></p><button onClick={() => { setNatRows(rows => [`10.24.0.25:51514 → 198.51.100.8:${nextPort} → 203.0.113.80:443`, ...rows].slice(0, 5)); setNextPort(port => port + 1); }} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Create outbound flow</button></div><div className="mt-4 space-y-2">{natRows.length ? natRows.map((row, i) => <div key={`${row}-${i}`} className="rounded-lg bg-slate-50 p-3 font-mono text-xs">{row}<span className="ml-2 text-emerald-700">· return mapping active</span></div>) : <p className="rounded-lg bg-slate-50 p-4 text-sm text-slate-500">No active example mappings. Create a flow to begin.</p>}</div><button onClick={() => { setNatRows([]); setNextPort(40001); }} className="mt-3 inline-flex items-center gap-2 text-xs font-semibold text-slate-600"><RotateCcw size={13}/>Reset flow table</button></div></section>
      <section id="cn2-routing" className="scroll-mt-32"><SectionTitle eyebrow="Hands-on lab 4" title="Test routing failover" text="This teaching model distinguishes an internal route from an upstream route. Toggle links and inspect whether an alternate is available."/><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="grid gap-4 sm:grid-cols-2"><LinkControl label="Primary upstream · eBGP" up={primaryUp} onToggle={() => setPrimaryUp(value => !value)}/><LinkControl label="Backup upstream · eBGP" up={backupUp} onToggle={() => setBackupUp(value => !value)}/></div><div className={`mt-4 rounded-xl p-4 text-sm ${primaryUp || backupUp ? 'bg-emerald-50 text-emerald-900' : 'bg-rose-50 text-rose-900'}`} role="status"><strong>{primaryUp ? 'Primary path available' : backupUp ? 'Primary failed; backup is available' : 'No upstream path available'}</strong><p className="mt-1">A backup only helps when configured, permitted by policy, and converged. An internal OSPF path does not itself restore an external BGP peering.</p></div><div className="mt-4 rounded-xl bg-slate-950 p-4 font-mono text-xs text-slate-200">Device ── OSPF domain ── Edge router ── {primaryUp ? 'Primary eBGP' : backupUp ? 'Backup eBGP' : '× disconnected'} ── Service network</div></div></section>
      <section id="cn2-forwarding" className="scroll-mt-32"><SectionTitle eyebrow="Concept workbench" title="Control plane and data plane" text="Try the terms together: routes and policy provide forwarding state; packet forwarding equipment applies that state."/><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5"><Network className="text-rose-600"/><h3 className="mt-3 font-bold">Control plane</h3><p className="mt-2 text-sm leading-6 text-slate-600">Protocols exchange reachability and calculate or select routes. Configuration and policy shape the result.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><ShieldCheck className="text-rose-600"/><h3 className="mt-3 font-bold">Data plane</h3><p className="mt-2 text-sm leading-6 text-slate-600">Switching and routing hardware or software uses installed forwarding state to handle traffic. Speed cannot repair incorrect state.</p></div></div></section>
      <section id="cn2-diagnosis" className="scroll-mt-32"><SectionTitle eyebrow="Practical case" title="The dispatch service is unreachable" text="Follow the evidence from local access toward the service. Stop at the first failing boundary, state a hypothesis, then choose one confirming test."/><DiagnosticLab/></section>
      <section id="cn2-recall" className="scroll-mt-32"><SectionTitle eyebrow="Check your understanding" title={`Question ${question + 1} of ${questions.length}`} text={quiz.q}/><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="grid gap-2">{quiz.options.map((option, i) => <button key={option} onClick={() => setAnswer(i)} className={`rounded-xl border p-4 text-left text-sm ${answer === i ? i === quiz.answer ? 'border-emerald-400 bg-emerald-50' : 'border-amber-400 bg-amber-50' : 'border-slate-200 hover:bg-slate-50'}`}>{option}</button>)}</div>{answer !== null && <p role="status" className="mt-4 rounded-xl bg-slate-50 p-4 text-sm leading-6"><strong>{answer === quiz.answer ? 'That’s right. ' : 'Review the idea. '}</strong>{quiz.why}</p>}<button onClick={() => { setQuestion(index => (index + 1) % questions.length); setAnswer(null); }} className="mt-4 rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Next question</button></div></section>
      <aside className="rounded-2xl border border-slate-200 bg-white p-5 text-sm text-slate-600"><CheckCircle2 className="mb-2 text-rose-600"/><strong className="text-slate-900">Learning scope</strong><p className="mt-2 leading-6">This is an independent study companion. The network and operations example is fictional, and the simulations illustrate concepts rather than reproducing any provider’s private infrastructure.</p><Link className="mt-3 inline-flex items-center gap-1 font-semibold text-rose-700" href="/interactive?course=computer-networks&module=computer-networks-unit-2">Open this module in the study lab <ArrowRight size={14}/></Link></aside>
    </main><footer className="flex flex-col items-center justify-center gap-2 border-t border-slate-200 bg-white py-8 text-xs text-slate-500 sm:flex-row sm:gap-5"><Link href="/notes/computer-networks/computer-networks-unit-1" className="font-semibold text-rose-700">← Back to Unit 1</Link><span>Computer Networks · Unit 2 · Independent interactive study module</span></footer>
  </div>;
}

function SectionTitle({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div className="mb-5"><p className="text-xs font-bold uppercase tracking-widest text-rose-600">{eyebrow}</p><h2 className="mt-2 text-2xl font-bold tracking-tight">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>; }
function LinkControl({ label, up, onToggle }: { label: string; up: boolean; onToggle: () => void }) { return <button aria-pressed={up} onClick={onToggle} className="flex items-center justify-between rounded-xl border border-slate-200 p-4 text-left"><span className="text-sm font-semibold">{label}</span><span className={`rounded-full px-3 py-1 text-xs font-bold ${up ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800'}`}>{up ? 'Available' : 'Failed'}</span></button>; }
function VlsmPlanner() {
  const entries = [{ name: 'Scanning devices', hosts: 180 }, { name: 'Staff', hosts: 50 }, { name: 'Management', hosts: 20 }, { name: 'Point-to-point', hosts: 2 }];
  const rows = useMemo(() => {
    let cursor = toNumber('10.24.0.0');
    const parentEnd = cursor + 1024n;
    return [...entries].sort((a, b) => b.hosts - a.hosts).map(entry => {
      const hostBits = Math.ceil(Math.log2(entry.hosts + 2));
      const size = 2n ** BigInt(hostBits);
      const network = ((cursor + size - 1n) / size) * size;
      const end = network + size;
      const valid = end <= parentEnd;
      cursor = end;
      return { ...entry, prefix: 32 - hostBits, network, end, size, valid };
    });
  }, []);
  return <div className="mt-5 min-w-0 rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-bold">VLSM allocation challenge</h3><p className="mt-1 text-sm text-slate-600">Fit the segments largest-first inside 10.24.0.0/22. The planner aligns each subnet boundary and flags allocations outside the parent block.</p><div className="mt-4 min-w-0 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead><tr className="border-b text-xs text-slate-500"><th className="p-2">Segment</th><th className="p-2">Hosts needed</th><th className="p-2">Allocated subnet</th><th className="p-2">Capacity</th></tr></thead><tbody>{rows.map(row => <tr key={row.name} className="border-b border-slate-100"><td className="p-2">{row.name}</td><td className="p-2">{row.hosts}</td><td className="p-2 font-mono">{row.valid ? `${toIp(row.network)}/${row.prefix}` : 'Does not fit'}</td><td className="p-2">{2 ** (32 - row.prefix) - 2} usable</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-slate-500">Point-to-point links commonly use /31 where supported; this simple allocation exercise uses /30 to illustrate the conventional two-host subnet rule.</p></div>;
}
function DiagnosticLab() {
  const [step, setStep] = useState(0);
  const checks = [
    ['Access and VLAN', 'Device receives an address; gateway link has normal error counters.'],
    ['Addressing and route', 'Route to the service prefix is present through the expected gateway.'],
    ['Translation and transport', 'A new flow has a live translation; connection to service port 443 times out.'],
    ['Application', 'Service responds after the network path and encrypted session complete.'],
  ];
  return <div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="mb-4 flex flex-wrap gap-2">{checks.map(([label], index) => <button key={label} onClick={() => setStep(index)} className={`rounded-full px-3 py-2 text-xs font-semibold ${step === index ? 'bg-slate-900 text-white' : 'border border-slate-200'}`}>{label}</button>)}</div><pre className="overflow-x-auto rounded-xl bg-slate-950 p-4 text-xs leading-6 text-slate-200">{checks[step]?.[1]}</pre><div className="mt-4 rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-950"><strong>Next reasoning step:</strong> {step === 2 ? 'Check the service listener and firewall/filter path for TCP port 443. A valid translation does not prove the remote port is reachable.' : step === 0 ? 'Check the device VLAN, IP configuration, gateway reachability, and access-link errors before moving upstream.' : step === 1 ? 'Compare the route table and next hop with a working device; then verify the outbound path.' : 'Now inspect service response and identity policy; successful routing is not the same as application success.'}</div><button onClick={() => setStep(index => (index + 1) % checks.length)} className="mt-4 rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Next diagnostic boundary</button></div>;
}
