import { notFound } from 'next/navigation';
const policies:Record<string,{title:string;sections:[string,string][]}>={
about:{title:'Independent by design.',sections:[['A companion to your studies','Aetheria organizes original study notes, syllabuses, and fictional practice cases. It is an independent project and is not affiliated with, endorsed by, or an official platform of any institution.'],['Learning with context','Public notes support understanding; consult your official curriculum, instructors, and authorized sources for assessment requirements.'],['Corrections','Please share suggested corrections with the administrator who provided your account, including the course and module title.']]},
privacy:{title:'Your study space. Your data.',sections:[['What is stored','Account details, a protected password hash, verification status, reading preferences, and administrative audit events are stored in the application database. When you use the AI tutor, your question and generated answer may be stored in your private conversation history.'],['AI processing','If you request an AI answer, your question and relevant published course material are sent to the configured AI provider. Restricted transcripts are not included in this release. Do not enter sensitive personal information.'],['Your choices','Public notes are available without an account. Contact your library administrator to request access, correction, export, or deletion of your account data. This application does not include advertising trackers.'],['Local preferences','Theme and reading size are stored on your device. Session cookies keep you signed in. Local development email stays in the local development inbox.']]},
terms:{title:'Study companion terms',sections:[['Independent learning support','The application provides educational assistance and does not award academic credit or represent an institution. You remain responsible for following your course policies and assessment rules.'],['Content and acceptable use','Use only original or authorized material. Do not upload private lectures, copyrighted notes, or personal data without permission. Do not attempt to access another person’s account or restricted material.'],['Generated explanations','AI may produce errors. Check citations and source notes. Fictional case studies are practice exercises, not reports of real businesses or professional advice.']]},
accessibility:{title:'Learning should be accessible.',sections:[['Reading preferences','Choose light, sepia, or dark mode using the theme control. In a note, change reading size from 85% to 140%. Browser zoom is supported.'],['Keyboard and navigation','Use Tab to reach controls and the skip link. Course notes have semantic headings and a linked table of contents. Reduced-motion preferences are respected.'],['Feedback','If you encounter an accessibility barrier, contact your library administrator with the page, browser, assistive technology, and a description of the issue.']]},
'content-policy':{title:'Original material. Clear sources.',sections:[['Independent project','Aetheria is an independent study companion. Any institutional course names are used for identification only and do not indicate endorsement.'],['Original demonstrations','Seeded course notes were written for this application. Demonstration case studies, businesses, and numerical examples are fictional and clearly labeled. Seeded notes are available under CC BY 4.0.'],['Publication responsibility','Editors must confirm their right to share material. Administrators control publication and can archive material. Drafts do not appear in the public library.'],['Corrections and removal','Contact your library administrator to flag a factual error, attribution issue, or content-removal request. Include the page address and the reason.']]}
};
export async function generateMetadata({params}:{params:Promise<{policy:string}>}){const {policy}=await params;return {title:policies[policy]?.title??'Page not found'}}
export default async function Policy({params}:{params:Promise<{policy:string}>}){const{policy}=await params;const p=policies[policy];if(!p)notFound();return <article className="policy-content"><p className="eyebrow">AETHERIA STUDY COMPANION</p><h1>{p.title}</h1>{p.sections.map(([heading,body])=><section key={heading}><h2>{heading}</h2><p>{body}</p></section>)}</article>}
